## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://localhost:3306/LoginNavidad?useSSL=false
userDB: root
passDB: nohay2sin3
mailFrom: user@gmail.com
smtpPort: 465
smtpServer: smtp.googlemail.com
mailPass: nohay2sin3
minutosParaValidar: 10
longitudCodigo: 50
